// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqyznjynjylhgfualvmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxeXpuanluanlsaGdmdWFsdm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODI2ODMsImV4cCI6MjA2NTE1ODY4M30.f7HlH45FTuMxxlhaZHzdiuGbT5IiOP5s5t3choTeZlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);